import streamlit as st
import yfinance as yf
import pandas as pd
import requests  # 👈 追加: Discord通信用
import json
from datetime import datetime, timedelta, timezone

# ==========================================
# ⚙️ 設定 (ここにURLを入れてください)
# ==========================================
DISCORD_WEBHOOK_URL ="https://discord.com/api/webhooks/1472281747000393902/Fbclh0R3R55w6ZnzhenJ24coaUPKy42abh3uPO-fRjfQulk9OwAq-Cf8cJQOe2U4SFme"

# ==========================================
# 📊 判定ロジック：MACD, RSI, 平均足
# ==========================================
def get_analysis(ticker, name):
    try:
        stock = yf.Ticker(ticker)
        # データ取得期間を少し長めに確保
        hist = stock.history(period="6mo")
        if len(hist) < 60: return None
        curr_price = int(hist["Close"].iloc[-1])

        # MACD
        ema12 = hist['Close'].ewm(span=12, adjust=False).mean()
        ema26 = hist['Close'].ewm(span=26, adjust=False).mean()
        macd = ema12 - ema26
        signal = macd.ewm(span=9, adjust=False).mean()
        
        # RSI
        delta = hist['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
        rsi_val = 100 - (100 / (1 + (gain / loss))).iloc[-1]

        # 反転フロア予測 (ボリンジャーバンド-2σ付近を想定)
        ma20 = hist['Close'].rolling(20).mean()
        std20 = hist['Close'].rolling(20).std()
        floor = max(int(ma20.iloc[-1] - (std20.iloc[-1] * 2)), int(hist['Low'].tail(60).min()))
        
        # MACDの状態判定
        macd_val = macd.iloc[-1]
        sig_val = signal.iloc[-1]
        macd_status = "GC(上昇)" if macd_val > sig_val else "DC(下落)"

        return {
            "コード": ticker.replace(".T", ""), 
            "銘柄名": name, 
            "現在値": curr_price,
            "RSI": round(rsi_val, 1), 
            "MACD": macd_status,
            "フロア": floor, 
            "指値目安": int(floor * 1.01),
            "利確目標": int(hist['High'].tail(25).max()), 
            "損切目安": int(floor * 0.97)
        }
    except Exception as e:
        return None

# ==========================================
# 📨 Discord送信機能 (新規追加！)
# ==========================================
def send_to_discord(data):
    if not DISCORD_WEBHOOK_URL.startswith("http"):
        st.error("⚠️ Webhook URLが設定されていません。コード内の `DISCORD_WEBHOOK_URL` を書き換えてください。")
        return

    # 見やすい「埋め込みメッセージ(Embed)」を作成
    payload = {
        "username": "最強株スキャナー🦅",
        "embeds": [
            {
                "title": f"📊 銘柄分析: {data['銘柄名']} ({data['コード']})",
                "description": f"**現在値: {data['現在値']}円**\nMACD: {data['MACD']} | RSI: {data['RSI']}",
                "color": 3066993,  # 緑色っぽいカラー
                "fields": [
                    {"name": "🛡️ 反転予想フロア", "value": f"{data['フロア']}円", "inline": True},
                    {"name": "🎯 利確目標", "value": f"{data['利確目標']}円", "inline": True},
                    {"name": "🛑 損切目安", "value": f"{data['損切目安']}円", "inline": True},
                    {"name": "⚡ 指値目安", "value": f"**{data['指値目安']}円**", "inline": False}
                ],
                "footer": {"text": "Generated by Hybrid-X Scanner"}
            }
        ]
    }
    
    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json=payload)
        if response.status_code == 204:
            st.toast("✅ Discordに通知を送信しました！", icon="🦅")
        else:
            st.error(f"送信失敗: {response.status_code}")
    except Exception as e:
        st.error(f"エラーが発生しました: {e}")

# ==========================================
# 🦅 画面表示
# ==========================================
st.set_page_config(page_title="最強株スキャナー", layout="wide")
st.title("🦅 最強株スキャナー (Discord連携版)")

# 翻訳エラー回避
st.markdown('<meta name="google" content="notranslate">', unsafe_allow_html=True)

code_in = st.text_input("銘柄コードを入力 (例: 6701, 9984)", "").strip()

if code_in:
    # 全角数字などを半角に変換したり、.Tをつける処理
    ticker_clean = code_in.replace(" ", "").replace("　", "")
    full_c = ticker_clean + ".T" if ".T" not in ticker_clean and ticker_clean.isdigit() else ticker_clean
    
    with st.spinner('市場データを分析中...'):
        res = get_analysis(full_c, ticker_clean)

    if res:
        # --- メイン情報の表示 ---
        c1, c2, c3 = st.columns(3)
        with c1:
            st.metric("現在値", f"{res['現在値']}円")
            st.info(f"🛡️ 反転予想フロア: {res['フロア']}円")
        with c2:
            st.success(f"⚡ 指値目安: {res['指値目安']}円")
            st.write(f"🎯 利確: {res['利確目標']}円 / 🛑 損切: {res['損切目安']}円")
        with c3:
            # RSIの色分け
            rsi_color = "red" if res['RSI'] < 30 else ("blue" if res['RSI'] > 70 else "black")
            st.markdown(f"MACD状態: **{res['MACD']}**")
            st.markdown(f"RSI(14): <span style='color:{rsi_color}; font-weight:bold;'>{res['RSI']}</span>", unsafe_allow_html=True)

        st.divider()

        # --- 👇 ここが追加機能：通知ボタン ---
        col_btn, col_void = st.columns([1, 4])
        with col_btn:
            if st.button('🦅 Discordに通知を送る'):
                send_to_discord(res)
    else:
        st.error("データが取得できませんでした。コードを確認してください。")
